version: "2.2"

x-lens2-environment: &lens2-environment
  # DataOS
  DATAOS_FQDN: liberal-donkey.dataos.app  
  # Overview
  LENS2_NAME: sales_analysis
  LENS2_DESCRIPTION: "Ecommerce use case on Adventureworks sales data"
  LENS2_TAGS: "sales and customer insights"
  LENS2_AUTHORS: "aayushisolanki, iamgroot"
  LENS2_SOURCE_TYPE: minerva
  LENS2_SOURCE_NAME: system
  LENS2_SOURCE_CATALOG_NAME: icebase
<<<<<<< HEAD:source/flash/docker-compose.yaml
  DATAOS_RUN_AS_APIKEY: dG9rZW5faW5maW5pdGVseV9uZWVkbGVzc2x5X2lkZWFsX2thdHlkaWQuODg4OGFmY2QtYjg2Zi00YWMwLWI5MjEtZmZmMGIwNjJlYjI0
=======
  DATAOS_RUN_AS_APIKEY: dG9rZW5fZ3JhdGVmdWxseV9ldmVubHlfb3Blbl9naWJib24uYzQ3MjAyNjItYTQ1ZC00MzM1LWE5ZjgtOGZjYWI2NDNjNzRl
>>>>>>> e3874cf2b3d44e397baa9506af5e5295bd60090c:docker-compose.yaml
  # Log
  LENS2_LOG_LEVEL: error
  CACHE_LOG_LEVEL: "error"
  # Operation
  LENS2_DEV_MODE: true   
  LENS2_REFRESH_WORKER: true
  LENS2_SCHEMA_PATH: model
  LENS2_PG_SQL_PORT: 5432
  CUBESTORE_DATA_DIR: "/var/work/.store"

services:
  api:
    restart: always
    image: rubiklabs/lens2:0.35.41-05   #.41-05 or .18-50
    ports:
      - 4000:4000
      - 25432:5432
      - 13306:13306
    environment:
      <<: *lens2-environment   
    volumes:
      - ./model:/etc/dataos/work/model