views:
  - name: transaction_success_rate
    description: Percentage of successful transactions
    public: true
    meta:
      tags:
        - DPDomain.Sales
        - DPUsecase.Performance Analysis
        - DPTier.Consumer Aligned
      metric:
        expression: "*/5  * * * *"
        timezone: "UTC"
        window: "day"
    tables:
      - join_path: transactions
        prefix: false
        includes:
          - successful_transactions #dimension
          - total_transactions  #measure
          - transaction_date  #time dimension
          - transaction_id #for the measuret that involves this dimension

 