views:
  - name: daily_revenue
    description: View containing sales 360 degree information
    public: true
    meta:
      tags:
        - DPDomain.Sales
        - DPUsecase.Purchasing Behaviour Analysis
        - DPTier.Consumer Aligned
      metric:
        expression: "*/5  * * * *"
        timezone: "UTC"
        window: "day"
        excludes:
          - sales.posting_date
    tables:
      - join_path: sales
        prefix: false
        includes:
          - revenue
          - ext_net
          - source
          - posting_date

  - name: total_invoices
    description: View containing sales 360 degree information
    public: true
    meta:
      tags:
        - DPDomain.Sales
        - DPUsecase.Purchasing Behaviour Analysis
        - DPTier.Consumer Aligned
      metric:
        expression: "*/5  * * * *"
        timezone: "UTC"
        window: "day"
    tables:
      - join_path: sales
        prefix: false
        includes:
          - total_invoices
          - invoice_no
          - invoice_date
          - posting_date
          - source